export const LOCATIONS_LIST_GET = 'LOCATIONS_LIST_GET';
export const LOCATIONS_LIST_GET_SUCCESS = 'LOCATIONS_LIST_GET_SUCCESS';
export const LOCATIONS_LIST_GET_ERROR = 'LOCATIONS_LIST_GET_ERROR';
export const LOCATIONS_LIST_SAVE = 'LOCATIONS_LIST_SAVE';
export const LOCATIONS_LIST_SAVE_SUCCESS = 'LOCATIONS_LIST_SAVE_SUCCESS';
export const LOCATIONS_LIST_SAVE_ERROR = 'LOCATIONS_LIST_SAVE_ERROR';

export const getLocationsList = () => ({
    type: LOCATIONS_LIST_GET,
});
