// @flow
export const GEOLOCATION_GET_POSITION = 'GEOLOCATION_GET_POSITION';
export const GEOLOCATION_GET_POSITION_SUCCESS = 'GEOLOCATION_GET_POSITION_SUCCESS';
export const GEOLOCATION_GET_POSITION_ERROR = 'GEOLOCATION_GET_POSITION_ERROR';

export const getPosition = () => ({
    type: GEOLOCATION_GET_POSITION,
});

